[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ["@aave/core-v3/contracts/=lib/aave-v3-core/contracts/",
        "@uniswap/v3-periphery/=lib/v3-periphery/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config